version: '3'

services:
  dash-app:
    build:
      context: .
      dockerfile: Dockerfile.dash
    ports:
      - "8050:8050"
    volumes:
      - ./saved_yamls:/app/saved_yamls
      - ./backups:/app/backups
    depends_on:
      - embedding-service
    environment:
      - EMBEDDING_SERVICE_URL=http://embedding-service:8000

  embedding-service:
    build:
      context: .
      dockerfile: Dockerfile.embedding
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=all-MiniLM-L6-v2
      - PORT=8000

